geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basket


app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
# from mainapp import urls
from . import views
from django.conf import settings
from django.conf.urls.static import static
from authapp import urls as authapp_urls
from mainapp import urls as mainapp_urls
from basketapp import urls as basketapp_urls
from adminapp import urls as adminapp_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),

    # path('products/', include(urls, namespace='products'), name='products'),
    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(mainapp_urls, namespace='products'), name='products'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),
    path('', views.index, name='index'),

    # path('<int:pk>', views.index, name='index'),
    # path('', views.index, name='products_all'),
    # path('', views.index, name='products_home'),

    path('contacts/', views.contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('product/<int:pk>/', products, name='products'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(urls)),
    path('', views.index),
    path('contacts/', views.contacts),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(
        verbose_name='описание',
        blank=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} - {self.id} -- {self.created}'

    class Meta:
        verbose_name = 'категория',
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
        verbose_name='фото товара',
    )
    short_desc = models.CharField(
        verbose_name='карткое описание товара',
        max_length=60,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание продукта',
        blank=True
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    updated = models.DateTimeField(
        auto_now=True
    )

    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} - {self.id} -- {self.created}'

    class Meta:
        verbose_name = 'продукт',
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from .models import Product, ProductCategory
import random


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None):
    title = 'каталог/продукты'

    links_menu = ProductCategory.objects.all()

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        # product = Product.objects.get(pk=pk)
        context = {
            'products': products,
            'title': title,
            'category': category,
            'links_menu': links_menu,
            'basket': basket,
        }
        return render(request, 'mainapp/products.html', context=context)

    # links_menu =[
    #    {'href': 'mainapp:index', 'name': 'все'},
    #    {'href': 'mainapp:index', 'name': 'дом'},
    #    {'href': 'mainapp:index', 'name': 'офис'},
    #    {'href': 'mainapp:index', 'name': 'модерн'},
    #    {'href': 'mainapp:index', 'name': 'классика'},
    # ]

    # products = Product.objects.all()
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'links_menu': links_menu,
        'title': title,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }
    return render(request, 'mainapp/products.html', context=context)

geekshop/mainapp/templates/mainapp/product.html
{% extends 'geekshop\base.html' %}
{% load static %}
{% block style %}
	<link rel="stylesheet" href="{% static '/mainapp/style.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/inc_main_menu.html' %}
		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">

				</ul>
			</div>
{{ product.name }}
		</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop\base.html' %}
{% load static %}
{% block style %}
	<link rel="stylesheet" href="{% static '/mainapp/style.css' %}">
{% endblock %}

{% block content %}
<div class="" style="padding-left: 100px; padding-right: 210px; position: relative;">
 	{% include 'includes/inc_main_menu.html' %}
	<div class="details">
		<div class="links clearfix">
			<ul class="links-menu">
				<li>
					<a href="{% url 'products:products' 0 %}"
					   class="{% if not request.resolver_match.kwargs.pk %}
								active
							  {% endif %}">
					  все
					</a>
				</li>
				{% for link in links_menu %}
					<li><a href="{% url 'products:products' pk=link.pk %}" {% if request.resolver_match.kwargs.pk == link.pk %} class="active" {% endif %}>{{link.name}}</a></li>
				{% endfor %}
			</ul>
		</div>

		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{hot_product.image}}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="/media/{{hot_product.image}}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{hot_product.image}}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{hot_product.image}}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">{{hot_product.name}}</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> {{hot_product.price}} <span>руб</span></p>
				<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					{{hot_product.description}}
				</div>
			</div>
		</div>

		<div>
			{% if category %}
			<h2>Категория: {{ category.name|title }}</h2>
			{% endif %}
		</div>

		<div class="products_category">
			{% for product in products %}
				<div class="block w-25 my-3 mx-3">
				  <a href="{% url 'basket:add' product.pk %}">
					<img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
					<div class="text">
					  <img src="{% static 'img/icon-hover.png' %}" alt="hover">
					  <h4>{{ product.name }}</h4>
					  <p>{{ product.description }} </p>
					</div>
				  </a>
				</div>
			{% endfor %}
		</div>


		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}